### ISSUE TITLE
DOMNodeAppear no longer working as of jQuery 3.0

### ISSUE THREAD

**Issue by chonax** [liamdanger/jQuery.DOMNodeAppear#6]
The $(this) object in the DOMNodeAppear function no longer has a "selector" property as of jQuery 3.0, and as such breaks JS with an error code: "Cannot read property 'replace' of undefined".  The "undefined" in this case is "$this.selector".

https://jquery.com/upgrade-guide/3.0/#breaking-change-deprecated-context-and-selector-properties-removed

**Comment by chonax** [comment]
I was able to temporarily detour this issue by editing DOMNodeAppear to receive two arguments instead of one, and then, in the function body, changing all references of "$this.selector" to "selector" which is the first argument received (the selector string).

I then call the function with:
"$.fn.DOMNodeAppear("selector string",function() { ... callback code ... }"

Its not as pretty as using the selector but it works.

**Comment by hawkeyetwolf** [comment]
@chonax, I'm about to do the same thing. How about making a PR with your changes and then I can work from that? ;) Thanks in advance!

**Comment by chonax** [comment]
Do you need to add me as a collaborator?  I have a fix ready to go but getting 403 Forbidden when pushing

**Comment by hawkeyetwolf** [comment]
Thanks, @chonax!

Try forking this repo and then pushing there. You should see an option to set this repo as the upstream. I dunno if the repo owner is still active here to merge in your change, but at least the PR branch will be available for others to use.

**Comment by liamdanger** [comment]
Yo! Sorry about the radio silence; I haven’t actively maintained this project for a good five years or so. I’d be happy to approve and merge a PR, or I could put up a deprecation notice on this repo and point to a fork as the successor. Let me know what you want to do ✌🏻

**Comment by hawkeyetwolf** [comment]
Thank you very much @liamdanger! I certainly know how it goes and appreciate you responding on this necro repo :) I created PR #7 to fix support in jQuery 3.0+. Let me know whatcha think. Cheers!

**Comment by chonax** [comment]
Hey sorry I couldnt get the pr in in time but glad to see the fix in place.  I use the moovweb platform to do mobile transformations and this function is the perfect tool to handle desktop content that arrives after the initial page load.  Glad to see it still being maintained.
